title: Heng Chen
url: ""
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"
kramdown:
  auto_ids: true

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about/"
 - name: "Research"
   link: "/research/"
 - name: "Media Coverage"
   link: "/briefings/"
 - name: "Contact"
   link: "/contact/"
